apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
type: Opaque
stringData:
  # Replace these in production (e.g., to point at AWS RDS)
  DATABASE_URL: "postgresql+psycopg2://postgres:postgres@postgres:5432/tododb"
